availableSecrets:
  secretManager:
    - versionName: projects/529419856712/secrets/billing_account/versions/latest
      env: "_BILLING"

steps:
# Initialize Terraform
- id: terraform init
  name: hashicorp/terraform:1.4.2
  entrypoint: sh
  args:
    - '-c'
    - |
        echo "Running init ..."
        cd terraform
        terraform init

  # Step 2: Validate Terraform code
- id: terraform-validate
  name: hashicorp/terraform:1.4.2
  entrypoint: sh
  args:
    - -c
    - |
      cd terraform
      terraform validate


# Generate and show a plan
- id: terraform plan
  name: hashicorp/terraform:1.4.2
  entrypoint: sh
  env:
    - "TF_VAR_billing_account=$_BILLING"
  secretEnv: ["_BILLING"]
  args:
    - '-c'
    - |
        echo "Running plan ..."
        cd terraform
        terraform plan -input=false -out=tfplan

# Generate and show a plan
- id: terraform apply
  name: hashicorp/terraform:1.4.2
  entrypoint: sh
  env:
    - "TF_VAR_billing_account=$_BILLING"
  secretEnv: ["_BILLING"]
  args:
    - '-c'
    - |
        echo "Running apply ..."
        cd terraform
        terraform aply -input=false -auto-approve -out=tfplan

options:
  logging: CLOUD_LOGGING_ONLY