availableSecrets:
  secretManager:
    - versionName: projects/529419856712/secrets/billing_account/versions/latest
      env: "_BILLING"

steps:
- id: zip
  name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args:
    - '-c'
    - |
      cd function
      zip -r function.zip index.js package.json

# Deploy to Cloud Run
- id: deploy-cloud-run
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - '-c'
    - |
      cd function
      gcloud run deploy visitor-function \
        --source . \
        --region northamerica-northeast2 \
        --platform managed \
        --allow-unauthenticated

# Initialize Terraform
- id: terraform init
  name: hashicorp/terraform:1.4.2
  entrypoint: sh
  args:
    - '-c'
    - |
        echo "Running init ..."
        cd terraform
        terraform init

  # Step 2: Validate Terraform code
- id: terraform-validate
  name: hashicorp/terraform:1.4.2
  entrypoint: sh
  args:
    - -c
    - |
      cd terraform
      terraform validate


# Generate and show a plan
- id: terraform plan
  name: hashicorp/terraform:1.4.2
  entrypoint: sh
  env:
    - "TF_VAR_billing_account=$_BILLING"
  secretEnv: ["_BILLING"]
  args:
    - '-c'
    - |
        echo "Running plan ..."
        cd terraform
        terraform plan -input=false -out=tfplan

# Generate and show a plan
- id: terraform apply
  name: hashicorp/terraform:1.4.2
  entrypoint: sh
  env:
    - "TF_VAR_billing_account=$_BILLING"
  secretEnv: ["_BILLING"]
  args:
    - '-c'
    - |
        echo "Running apply ..."
        cd terraform
        terraform apply -input=false -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY